[package]
name = "reth-optimism-node"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# reth
reth-chainspec = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
## ensure secp256k1 recovery with rayon support is activated
reth-primitives-traits = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1", features = ["secp256k1", "rayon"] }
reth-payload-builder = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-consensus = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-node-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-node-builder = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-tracing = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-provider = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-transaction-pool = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-network = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-evm = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-rpc-server-types = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-tasks = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1", optional = true }
reth-trie-common = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-node-core = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-rpc-engine-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-engine-local = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1", features = ["op"] }
reth-rpc-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }

# op-reth
reth-optimism-payload-builder = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-optimism-evm = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1", features = ["std", "rpc"] }
reth-optimism-rpc.workspace = true
reth-optimism-storage = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-optimism-txpool = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-optimism-chainspec = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-optimism-consensus = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1", features = ["std"] }
reth-optimism-forks = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-optimism-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1", features = ["serde", "serde-bincode-compat", "reth-codec"] }

# revm with required optimism features
# Note: this must be kept to ensure all features are properly enabled/forwarded
revm = { workspace = true, features = ["secp256k1", "blst", "c-kzg", "memory_limit"] }
op-revm.workspace = true

# ethereum
alloy-primitives.workspace = true
op-alloy-consensus.workspace = true
op-alloy-rpc-types-engine.workspace = true
alloy-rpc-types-engine.workspace = true
alloy-rpc-types-eth.workspace = true
alloy-consensus.workspace = true

# async
tokio.workspace = true

# misc
clap.workspace = true
serde.workspace = true
eyre.workspace = true
url.workspace = true

# test-utils dependencies
reth-e2e-test-utils = { workspace = true, optional = true }
alloy-genesis = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }

[dev-dependencies]
reth-optimism-node = { workspace = true, features = ["test-utils"] }
reth-db = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1", features = ["op", "test-utils"] }
reth-node-builder = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1", features = ["test-utils"] }
reth-provider = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1", features = ["test-utils"] }
reth-tasks = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-payload-util = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-revm = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1", features = ["std"] }
reth-rpc = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-rpc-eth-types = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-stages-types = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-trie-db = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }

alloy-network.workspace = true
alloy-op-hardforks.workspace = true
futures.workspace = true
op-alloy-network.workspace = true

[features]
default = ["reth-codec"]
asm-keccak = [
    "alloy-primitives/asm-keccak",
    "reth-optimism-node/asm-keccak",
    "reth-node-core/asm-keccak",
    "revm/asm-keccak",
]
keccak-cache-global = [
    "alloy-primitives/keccak-cache-global",
    "reth-node-core/keccak-cache-global",
    "reth-optimism-node/keccak-cache-global",
]
js-tracer = [
    "reth-node-builder/js-tracer",
    "reth-optimism-node/js-tracer",
    "reth-rpc/js-tracer",
    "reth-rpc-eth-types/js-tracer",
]
test-utils = [
    "reth-tasks",
    "reth-e2e-test-utils",
    "alloy-genesis",
    "serde_json",
    "reth-node-builder/test-utils",
    "reth-chainspec/test-utils",
    "reth-consensus/test-utils",
    "reth-evm/test-utils",
    "reth-network/test-utils",
    "reth-payload-builder/test-utils",
    "reth-revm/test-utils",
    "reth-db/test-utils",
    "reth-provider/test-utils",
    "reth-transaction-pool/test-utils",
    "reth-optimism-node/test-utils",
    "reth-optimism-primitives/arbitrary",
    "reth-primitives-traits/test-utils",
    "reth-trie-common/test-utils",
    "reth-trie-db/test-utils",
    "reth-stages-types/test-utils",
]
reth-codec = ["reth-optimism-primitives/reth-codec"]

[[test]]
name = "e2e_testsuite"
path = "tests/e2e-testsuite/main.rs"
