[package]
name = "reth-optimism-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
reth-static-file-types = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1", features = ["clap"] }
reth-cli = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-cli-commands = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-consensus = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-rpc-server-types = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-primitives-traits = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-db = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1", features = ["mdbx", "op"] }
reth-db-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-db-common = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-downloaders = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-provider = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-prune = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-stages = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-static-file = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-execution-types = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-node-core = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-optimism-node.workspace = true
reth-fs-util = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }

# so jemalloc metrics can be included
reth-node-metrics.workspace = true

## optimism
reth-optimism-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-optimism-chainspec = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1", features = ["superchain-configs"] }
reth-optimism-consensus = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-optimism-trie.workspace = true

reth-chainspec = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-node-events = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-optimism-evm = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-cli-runner = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-node-builder = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1", features = ["op"] }
reth-tracing = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }

# eth
alloy-eips.workspace = true
alloy-consensus.workspace = true
alloy-primitives.workspace = true
alloy-rlp.workspace = true

# misc
futures-util.workspace = true
derive_more.workspace = true
serde.workspace = true
clap = { workspace = true, features = ["derive", "env"] }

tokio = { workspace = true, features = ["sync", "macros", "time", "rt-multi-thread"] }
tokio-util = { workspace = true, features = ["codec"] }
tracing.workspace = true
eyre.workspace = true

# reth test-vectors
proptest = { workspace = true, optional = true }
op-alloy-consensus.workspace = true

[dev-dependencies]
tempfile.workspace = true
reth-stages = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1", features = ["test-utils"] }

[build-dependencies]
reth-optimism-chainspec = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1", features = ["std", "superchain-configs"] }

[features]
default = []

# Opentelemetry feature to activate tracing and logs export
otlp = ["reth-tracing/otlp", "reth-node-core/otlp"]
otlp-logs = ["reth-tracing/otlp-logs", "reth-node-core/otlp-logs"]

asm-keccak = [
    "alloy-primitives/asm-keccak",
    "reth-node-core/asm-keccak",
    "reth-optimism-node/asm-keccak",
]

keccak-cache-global = [
    "alloy-primitives/keccak-cache-global",
    "reth-node-core/keccak-cache-global",
    "reth-optimism-node/keccak-cache-global",
]

# Jemalloc feature for vergen to generate correct env vars
jemalloc = [
    "reth-node-core/jemalloc",
    "reth-node-metrics/jemalloc",
]
jemalloc-prof = [
    "jemalloc",
    "reth-node-metrics/jemalloc-prof",
]
jemalloc-symbols = [
    "jemalloc-prof",
    "reth-node-metrics/jemalloc-symbols",
]

tracy = ["reth-tracing/tracy", "reth-node-core/tracy"]

dev = ["dep:proptest", "reth-cli-commands/arbitrary"]

serde = [
    "alloy-consensus/serde",
    "alloy-eips/serde",
    "alloy-primitives/serde",
    "op-alloy-consensus/serde",
    "reth-execution-types/serde",
    "reth-optimism-primitives/serde",
    "reth-primitives-traits/serde",
    "reth-optimism-chainspec/serde",
]

edge = ["reth-cli-commands/edge", "reth-node-core/edge"]
