[package]
name = "reth-optimism-exex"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Execution extensions for OP-Reth"

[lints]
workspace = true

[dependencies]
# reth
reth-exex = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-execution-types = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-node-types = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-node-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-trie = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-provider = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }

# op-reth
# proofs exex handles `TrieUpdates` in notifications
reth-optimism-trie = { workspace = true, features = ["serde-bincode-compat"] }

# alloy
alloy-consensus.workspace = true
alloy-eips.workspace = true

# misc
eyre.workspace = true
futures-util.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["test-util", "rt-multi-thread", "macros"] }
futures.workspace = true
reth-db = { workspace = true, features = ["op", "test-utils"] }
reth-node-builder = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-optimism-node = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-optimism-chainspec = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-primitives-traits = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-ethereum-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-exex-test-utils = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
tempfile.workspace = true

[features]
test-utils = [
    "reth-db/test-utils",
    "reth-trie/test-utils",
    "reth-node-builder/test-utils",
    "reth-optimism-node/test-utils",
    "reth-provider/test-utils",
    "reth-ethereum-primitives/test-utils",
    "reth-primitives-traits/test-utils",
]
metrics = ["reth-optimism-trie/metrics"]

[package.metadata.cargo-udeps.ignore]
development = [
    "reth-node-builder",
    "reth-optimism-node",
    "reth-optimism-chainspec",
    "tempfile.workspace",
]
