[package]
name = "reth-optimism-trie"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Trie node storage for serving proofs in FP window fast"

[lints]
workspace = true

[dependencies]
# reth
reth-db = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1", features = ["mdbx"] }
reth-evm = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-execution-errors = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-primitives-traits = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-provider = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-revm = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-trie = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1", features = ["serde"] }
reth-trie-common = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1", features = ["serde"] }
reth-tasks = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }

# `metrics` feature
metrics = { workspace = true, optional = true }
reth-metrics = { workspace = true, features = ["common"], optional = true }

# ethereum
alloy-primitives.workspace = true
alloy-eips.workspace = true

# async
tokio = { workspace = true, features = ["sync"] }

# codec
bytes.workspace = true
serde.workspace = true
bincode.workspace = true

# misc
thiserror.workspace = true
auto_impl.workspace = true
eyre.workspace = true
strum.workspace = true
tracing.workspace = true
derive_more.workspace = true

[dev-dependencies]
reth-codecs = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1", features = ["test-utils"] }
tempfile.workspace = true
tokio = { workspace = true, features = ["test-util", "rt-multi-thread", "macros"] }
test-case.workspace = true
reth-db = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1", features = ["test-utils"] }
# workaround for failing doc test <https://github.com/op-rs/op-reth/pull/234>
reth-db-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1", features = ["test-utils"] }
reth-trie = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1", features = ["test-utils"] }
reth-provider = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1", features = ["test-utils"] }
reth-node-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
alloy-consensus.workspace = true
alloy-genesis.workspace = true
reth-chainspec = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-db-common = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-ethereum-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-evm-ethereum = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-testing-utils = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
reth-storage-errors = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.1" }
secp256k1.workspace = true
mockall.workspace = true

# misc
serial_test.workspace = true

[features]
serde-bincode-compat = [
    "reth-primitives-traits/serde-bincode-compat",
    "reth-trie-common/serde-bincode-compat",
    "alloy-consensus/serde-bincode-compat",
    "alloy-eips/serde-bincode-compat",
    "alloy-genesis/serde-bincode-compat",
    "reth-ethereum-primitives/serde-bincode-compat",
]
metrics = [
    "reth-trie/metrics",
    "dep:reth-metrics",
    "dep:metrics",
]
